import Layout from '@/components/layout'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import AnimatedText from '@/components/AnimatedText'
import profilePic from "../../public/images/profile/developer-pic-1.png";
import { LinkArrow } from '@/components/Icons'
import Footer from '@/components/Footer'
import { HireMe } from '@/components/HireMe'
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg"
import { Skills } from '@/components/Skills'
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        
      </Head>
      <main className='flex items-center text-dark w-full min-h-screen'> 
        <Layout className='pt-0'>
          <div className="flex items-center justify-between w-full">
            <div className='w-1/2'>
              <Image src={profilePic} alt="Yogesh" className='w-full h-auto'/>
            </div>
            <div className='w-1/2 flex flex-col items-center self-center'>
            
              <AnimatedText text="Turning Vision Into Reality With Code And Design." className='!text-6xl !text-left'/>
              <p className='my-4 text-base font-medium'></p>
              <p>As a skilled full-stack developer, I am dedicated to turning ideas into innovative web applications. 
              Explore my latest projects , showcasing my expertise in web development.</p>
              <div className='flex items-center self-start mt-2'>
                <Link href="/Yogesh Kumar Sharma.pdf" target={'_blank'}
                className='flex items-center bg-dark text-light p-2.5 px-6
                rounded-lg text-lg font-senibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark'
                download={true}>Resume <LinkArrow className={"w-6 ml-1"}></LinkArrow>
                </Link>
                <Link href="mailto:yk9604870@gmail.com" target={'_blank'}
                className='ml-4 text-lg font-medium capitalize text-dark underline'
                >Contact</Link>
              </div>
            </div>
            </div>
        </Layout>
        <HireMe />
        <div className='absoulte right-8 bottom-8 inline-block w-24'>
          <Image src={lightBulb} alt="Yogeshsharma" className='w-full h-auto'/>
        </div>
      </main>
    </>
  )
}
